# Generated by Django 4.1 on 2022-09-14 14:11

import distutils.command.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_image', models.ImageField(upload_to='', verbose_name=distutils.command.upload.upload)),
                ('features_price', models.CharField(max_length=10)),
                ('features_rating_icon1', models.CharField(max_length=30)),
                ('features_rating_icon2', models.CharField(max_length=30)),
                ('features_rating_icon3', models.CharField(max_length=30)),
                ('features_rating_icon4', models.CharField(max_length=30)),
                ('features_rating_icon5', models.CharField(max_length=30)),
                ('features_heading', models.CharField(max_length=100)),
                ('features_details', models.TextField()),
                ('features_location', models.CharField(max_length=40)),
                ('features_days', models.CharField(max_length=10)),
                ('features_nights', models.CharField(max_length=10)),
            ],
        ),
    ]
