# Generated by Django 4.1 on 2022-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='features_image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
